'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'id' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  id: {
    // Nav
    'nav.dashboard': 'Dashboard',
    'nav.dispenser': 'Terminal Dispenser',
    'nav.history': 'Histori Bulanan',
    'nav.backdate': 'Input Susulan',
    'nav.units': 'Unit Armada',
    'nav.tanks': 'Tangki Solar',
    'nav.users': 'Kelola Pengguna',
    'nav.audit': 'Jejak Audit',
    'nav.menu': 'Menu Utama',
    'nav.networkActive': 'Jaringan Aktif',

    // Header & Profile
    'header.wita': 'WITA (Waktu Site)',
    'header.wib': 'WIB',
    'header.shift1': 'Shift 1 (Siang)',
    'header.shift2': 'Shift 2 (Malam)',
    'header.exportExcel': 'Ekspor Excel',
    'header.sheets': 'Google Sheets',
    'profile.title': 'Profil Pengguna',
    'profile.account': 'Informasi Akun',
    'profile.role': 'Peran',
    'profile.language': 'Bahasa / Language',
    'profile.languageLabel': 'Bahasa',
    'profile.theme': 'Tema Tampilan',
    'profile.themeLabel': 'Tema',
    'profile.darkModeLabel': 'Tema',
    'profile.light': 'Terang',
    'profile.dark': 'Gelap',
    'profile.signOut': 'Keluar Akun',
    'profile.logoutLabel': 'Keluar',

    // Dashboard
    'dash.title': 'Dashboard Operasional Bahan Bakar',
    'dash.subtitle': 'Monitoring Inventori Solar B35, Konsumsi Armada, & Sinkronisasi Site',
    'dash.liveTelemetry': 'Telemetri Aktif',
    'dash.siteName': 'PT Batara Perkasa • Site Kutai Barat',
    'dash.recordDispense': 'Catat Pengisian (Dispenser)',
    'dash.totalDispensedToday': 'Solar Keluar (Hari Ini)',
    'dash.totalDispensedMonth': 'Total Bulan Ini',
    'dash.totalTransactions': 'Transaksi Dispenser',
    'dash.inboundRefills': 'BBM Masuk (Supplier)',
    'dash.activeFleet': 'Armada Beroperasi',
    'dash.storageTanksTitle': 'Status Tangki Penyimpanan',
    'dash.storageTanksSubtitle': 'Stok Solar B35 Industrial Storage',
    'dash.actualStock': 'Stok Aktual',
    'dash.maxCapacity': 'Kapasitas Penuh',
    'dash.remainingUllage': 'Sisa Ruang (Ullage)',
    'dash.criticalLimit': 'Batas Minimum Alert',
    'dash.shiftSummaryTitle': 'Status Shift & Armada',
    'dash.activeShift': 'Shift Operasional',
    'dash.dutyOfficer': 'Petugas Jaga',
    'dash.recentLogsTitle': 'Log Transaksi Pengisian Terkini',
    'dash.recentLogsSubtitle': 'Audit real-time pengisian unit alat berat',
    'dash.filterPlaceholder': 'Filter No Unit (misal: LV, DT, EX)...',
    'dash.viewFullHistory': 'Lihat Semua di Histori Bulanan',
    'dash.synced': 'Tersinkron',
    'dash.pending': 'Menunggu Sync',
    'dash.totalDispensed': 'Solar Tersalurkan',
    'dash.totalStock': 'Total Stok Tangki',
    'dash.activeUnits': 'Unit Armada Aktif',
    'dash.openSheets': 'Buka Google Sheets Live',
    'dash.downloadExcel': 'Unduh Laporan Excel Bulanan',
    'dash.noUnit': 'No Unit',
    'dash.category': 'Kategori',
    'dash.dateTime': 'Waktu (WITA)',
    'dash.volume': 'Volume (L)',
    'dash.operator': 'Operator',
    'dash.fuelman': 'Fuelman',
    'dash.viewAll': 'Kelola Tangki',
    'dash.fleetDistribution': 'Distribusi Unit Armada Terdaftar',
    'dash.shiftDay': 'Siang',
    'dash.shiftNight': 'Malam',
    'dash.capacityLabel': 'Kapasitas',
    'dash.shiftActive': 'Shift 1 & 2 Aktif',
    'dash.totalRecords': 'Total Data Site',
    'dash.tickets': 'Tiket',
    'dash.filled': 'Terisi',
    'dash.loadingTanks': 'Memuat data tangki penyimpanan...',
    'dash.logsCount': 'Ditampilkan',

    // Dispenser Page
    'dispenser.title': 'Terminal Pengisian Bahan Bakar',
    'dispenser.subtitle': 'Validasi delta meter real-time, pencatatan transaksi, dan sinkronisasi otomatis Google Sheets',
    'dispenser.fuelDispensed': 'Solar Tersalurkan',
    'dispenser.transactions': 'Jumlah Transaksi',
    'dispenser.inboundRefills': 'BBM Masuk (Supplier)',
    'dispenser.dutyOfficer': 'Petugas Jaga',
    'dispenser.docketTitle': 'Doket Pengisian Solar',
    'dispenser.docketSubtitle': 'Validasi Delta Engine Aktif',
    'dispenser.keypadOn': 'Keypad Nyala',
    'dispenser.keypadOff': 'Keypad Mati',
    'dispenser.selectUnit': 'Pilih Unit Alat Berat Target',
    'dispenser.searchUnitPlaceholder': '-- Cari atau pilih unit fleet target --',
    'dispenser.odometerKm': 'Odometer Terkini (KM)',
    'dispenser.prevKm': 'Sebelumnya',
    'dispenser.hourMeterHm': 'Hour Meter Terkini (HM)',
    'dispenser.prevHm': 'Sebelumnya',
    'dispenser.dispenseQty': 'Kuantitas Keluar (QTY OUT - Liter)',
    'dispenser.tapPresets': 'Sentuh Preset',
    'dispenser.operatorDriver': 'Operator / Driver',
    'dispenser.searchOperatorPlaceholder': 'Cari atau ketik nama operator...',
    'dispenser.recordAndSync': 'Submit',
    'dispenser.recording': 'Menyimpan Transaksi...',
    'dispenser.inspectBaselines': 'Pilih Unit untuk Memeriksa Nilai Acuan',
    'dispenser.inspectDesc': 'Kalkulasi delta membandingkan dengan catatan Hour Meter dan Odometer terakhir secara real-time.',
    'dispenser.plateNumber': 'Nomor Plat',
    'dispenser.status': 'Status',
    'dispenser.lastKm': 'KM Terakhir',
    'dispenser.lastHm': 'HM Terakhir',
    'dispenser.errEnterVolume': 'Harap masukkan volume pengisian dalam satuan Liter.',
    'dispenser.errEnterOperator': 'Harap isi nama pengemudi / operator unit.',

    // History Page
    'history.title': 'Histori Bulanan Transaksi',
    'history.subtitle': 'Eksplorasi, input susulan, dan sinkronisasi buku besar bahan bakar per tab bulan',
    'history.syncMonth': 'Sinkronkan Bulan',
    'history.syncing': 'Menyinkronkan...',
    'history.syncMaster': 'Sinkronkan Master Log',
    'history.inputBackdate': 'Input Susulan',
    'history.addEntry': 'Tambah Entri',
    'history.importExcel': 'Impor Data Excel',
    'history.fuelDispensed': 'Solar Tersalurkan',
    'history.inboundRefills': 'BBM Masuk',
    'history.restocked': 'Restok Masuk',
    'history.transactions': 'Total Transaksi',
    'history.monthlyRecords': 'Catatan Bulanan',
    'history.activeUnits': 'Unit Beroperasi',
    'history.fuelledFleets': 'Armada Terisi',
    'history.sheetSync': 'Sinkronisasi Tab Sheets',
    'history.searchPlaceholder': 'Cari no unit, operator, fuelman, atau kategori...',
    'history.shiftFilter': 'Shift',
    'history.allShifts': 'SEMUA SHIFT',
    'history.shift1': 'SHIFT 1 (Siang)',
    'history.shift2': 'SHIFT 2 (Malam)',
    'history.syncFilter': 'Status Sync',
    'history.allStatus': 'SEMUA STATUS',
    'history.synced': 'TERKIRIM (SYNCED)',
    'history.pending': 'MENUNGGU (PENDING)',
    'history.failed': 'GAGAL (FAILED)',
    'history.colNo': 'NO ID.',
    'history.colUnit': 'NO UNIT',
    'history.colCategory': 'KATEGORI',
    'history.colMerk': 'MERK / TYPE',
    'history.colType': 'TYPE',
    'history.colDate': 'TANGGAL',
    'history.colTime': 'JAM',
    'history.colKm': 'KM',
    'history.colHm': 'HM',
    'history.colFuelIn': 'BBM MASUK',
    'history.colQtyOut': 'QTY KELUAR ( L )',
    'history.colOperator': 'OPERATOR',
    'history.colShift': 'SHIFT',
    'history.colFuelman': 'FUELMAN',
    'history.colTank': 'TANGKI',
    'history.colSync': 'SYNC SHEETS',
    'history.colActions': 'AKSI',
    'history.noTransactions': 'Belum ada transaksi pengisian pada periode ini.',
    'history.loadingMonth': 'Memuat catatan histori...',
    'history.dismiss': 'Tutup',

    // Backdate Page
    'backdate.title': 'Input Transaksi Susulan (Backdate)',
    'backdate.subtitle': 'Penginputan transaksi pengisian bahan bakar yang terlewat dengan validasi kronologis aturan HM & KM.',
    'backdate.preset': 'Pilihan Cepat:',
    'backdate.yesterday': 'Kemarin',
    'backdate.twoDaysAgo': '2 Hari Lalu',
    'backdate.today': 'Hari Ini',
    'backdate.monthlyHistory': 'Histori Bulanan',
    'backdate.close': 'Tutup',
    'backdate.dateLabel': 'Tanggal Pengisian',
    'backdate.timeLabel': 'Waktu / Jam (WITA)',
    'backdate.shiftLabel': 'Shift Operasional',
    'backdate.fuelmanLabel': 'Petugas Fuelman',
    'backdate.selectUnitLabel': 'Pilih Unit Alat Berat',
    'backdate.selectTankLabel': 'Pilih Tangki Pengambilan',
    'backdate.operatorLabel': 'Operator / Driver',
    'backdate.qtyLabel': 'Jumlah Solar Keluar (QTY OUT - Liter)',
    'backdate.fuelInLabel': 'BBM Masuk dari Supplier (Bila Ada - Liter)',
    'backdate.submit': 'Submit',
    'backdate.saving': 'Menyimpan Transaksi Susulan...',
    'backdate.bypassWarning': 'Mode Bypass Validasi Diaktifkan',
    'backdate.chronologicalSummary': 'Audit Kronologis & Batas Meter',

    // Units Page
    'units.title': 'Master Unit Armada & Alat Berat',
    'units.subtitle': 'Daftar armada, kalibrasi acuan KM/HM, dan status operasional',
    'units.importExcel': 'Impor Excel',
    'units.addUnit': 'Tambah Unit',
    'units.searchPlaceholder': 'Cari no unit, plat nomor, kategori, atau tipe merk...',
    'units.colCode': 'NO UNIT',
    'units.colPlate': 'PLAT NOMOR',
    'units.colCategory': 'KATEGORI',
    'units.colModel': 'MERK / MODEL',
    'units.colType': 'TYPE',
    'units.colLastKm': 'KM TERAKHIR',
    'units.colLastHm': 'HM TERAKHIR',
    'units.colStatus': 'STATUS',
    'units.colActions': 'AKSI',
    'units.active': 'Aktif',
    'units.inactive': 'Nonaktif',
    'units.edit': 'Ubah',
    'units.delete': 'Hapus',
    'units.modalTitleCreate': 'Pendaftaran Unit Baru',
    'units.modalTitleEdit': 'Ubah Data Unit',
    'units.unitCodeLabel': 'Kode Unit (misal: DT-01, EX-200)',
    'units.plateLabel': 'Nomor Polisi / Plat',
    'units.categoryLabel': 'Kategori Armada',
    'units.typeLabel': 'Tipe Unit (Vehicle Type)',
    'units.modelLabel': 'Merk & Model',
    'units.save': 'Simpan Unit',
    'units.saving': 'Menyimpan...',
    'units.cancel': 'Batal',
    'units.emptyTitle': 'Tidak ada unit armada ditemukan',

    // Tanks Page
    'tanks.title': 'Manajemen Tangki Solar B35',
    'tanks.subtitle': 'Pengawasan stok fisik, batas minimum aman, dan pencatatan restock solar supplier',
    'tanks.addTank': 'Daftarkan Tangki Baru',
    'tanks.recordRefill': 'Catat BBM Masuk (Refill)',
    'tanks.currentStock': 'Stok Aktual',
    'tanks.capacity': 'Kapasitas Penuh',
    'tanks.minAlert': 'Batas Minimum Alert',
    'tanks.availableUllage': 'Sisa Ruang Kosong (Ullage)',
    'tanks.availableFuel': 'Stok Tersedia',
    'tanks.full': 'Terisi',
    'tanks.tankCode': 'Kode Tangki',
    'tanks.tankName': 'Nama Tangki',
    'tanks.fuelType': 'Jenis Bahan Bakar / Grade',
    'tanks.capacityL': 'Kapasitas (L)',
    'tanks.currentStockL': 'Stok Saat Ini (L)',
    'tanks.alertLevelL': 'Batas Peringatan Minimum (L)',
    'tanks.refillModalTitle': 'Catat Solar Masuk (Refill Tangki)',
    'tanks.refillVolume': 'Volume Masuk (BBM Masuk - Liter)',
    'tanks.refillNotes': 'Catatan Pengiriman / No Surat Jalan',
    'tanks.saveRefill': 'Simpan Refill',
    'tanks.saving': 'Menyimpan...',
    'tanks.editTank': 'Ubah Tangki',
    'tanks.deleteTank': 'Hapus Tangki',
    'tanks.createModalTitle': 'Pendaftaran Tangki Baru',
    'tanks.editModalTitle': 'Ubah Data Tangki',
    'tanks.deleteConfirm': 'Apakah Anda yakin ingin menghapus tangki penyimpanan ini secara permanen? Tangki dengan catatan transaksi histori tidak dapat dihapus.',
    'tanks.confirmDelete': 'Konfirmasi Hapus',
    'tanks.confirmInbound': 'Konfirmasi BBM Masuk',
    'tanks.processing': 'Memproses...',

    // Users Page
    'users.title': 'Manajemen Pengguna & Otoritas',
    'users.subtitle': 'Pengaturan akses sistem, registrasi personel site, dan kontrol keamanan akun',
    'users.addUser': 'Tambah Pengguna',
    'users.totalUsers': 'Total Pengguna',
    'users.activeAccounts': 'Akun Aktif',
    'users.administrators': 'Administrator',
    'users.fuelmenOfficers': 'Fuelman / Petugas',
    'users.registered': 'terdaftar',
    'users.fieldCrew': 'petugas lapangan',
    'users.rootPrivileged': 'akses penuh',
    'users.searchPlaceholder': 'Cari nama lengkap, username, atau email...',
    'users.roleFilter': 'Peran',
    'users.allRoles': 'Semua Peran',
    'users.admins': 'Admin',
    'users.management': 'Management',
    'users.fuelmen': 'Fuelman',
    'users.statusFilter': 'Status Akun',
    'users.allStatus': 'Semua Status',
    'users.active': 'Aktif',
    'users.inactive': 'Nonaktif',
    'users.colUser': 'PENGGUNA / IDENTITAS',
    'users.colEmail': 'ALAMAT EMAIL',
    'users.colRole': 'PERAN',
    'users.colStatus': 'STATUS',
    'users.colDispenseLogs': 'LOG PENGISIAN',
    'users.colCreated': 'TERDAFTAR',
    'users.colActions': 'AKSI',
    'users.loadingUsers': 'Memuat akun pengguna...',
    'users.noUsersFound': 'Tidak ada pengguna yang cocok dengan kriteria pencarian.',
    'users.you': 'Anda',
    'users.clickToDeactivate': 'Klik untuk Nonaktifkan',
    'users.clickToActivate': 'Klik untuk Aktifkan',
    'users.editUser': 'Ubah Pengguna',
    'users.deleteUser': 'Hapus Pengguna',
    'users.createModalTitle': 'Registrasi Akun Pengguna Baru',
    'users.editModalTitle': 'Ubah Data Pengguna',
    'users.username': 'Username',
    'users.systemRole': 'Peran Sistem',
    'users.fullName': 'Nama Lengkap',
    'users.emailAddress': 'Alamat Email',
    'users.initialPassword': 'Kata Sandi Awal',
    'users.resetPassword': 'Atur Ulang Kata Sandi',
    'users.optional': 'opsional',
    'users.leaveBlank': 'Kosongkan jika tidak ingin mengubah kata sandi',
    'users.accountStatus': 'Status Akun',
    'users.activeDesc': 'Aktif dan diizinkan masuk sistem',
    'users.inactiveDesc': 'Akun dinonaktifkan',
    'users.cannotDeactivateSelf': 'Anda tidak dapat menonaktifkan akun sendiri',
    'users.deleteConfirm': 'Apakah Anda yakin ingin menghapus pengguna ini secara permanen? Tindakan ini tidak dapat dibatalkan dan akan dicatat dalam jejak audit.',
    'users.deleteWarningHasLogs': 'Peringatan: Pengguna ini telah mencatat log pengisian bahan bakar dan tidak dapat dihapus secara permanen. Anda sebaiknya menonaktifkan akun ini.',
    'users.deactivateInstead': 'Nonaktifkan Akun Saja',
    'users.confirmDelete': 'Konfirmasi Hapus',
    'users.accessRestricted': 'Akses Terbatas',
    'users.accessRestrictedDesc': 'Manajemen Pengguna hanya dapat diakses oleh administrator sistem yang berwenang.',
    'users.returnToDispenser': 'Kembali ke Dispenser',

    // Audit Page
    'audit.title': 'Jejak Audit & Keamanan Sistem',
    'audit.subtitle': 'Log permanen seluruh aktivitas transaksi, bypass validasi, dan perubahan administratif',
    'audit.colTimestamp': 'WAKTU (WITA/WIB)',
    'audit.colAction': 'AKSI SISTEM',
    'audit.colEntity': 'ENTITAS',
    'audit.colUser': 'DILAKUKAN OLEH',
    'audit.colIp': 'IP / KLIEN',
    'audit.colDetails': 'PERUBAHAN / ALASAN',
    'audit.systemWorker': 'Pekerja Sistem',

    // Login Page
    'login.title': 'BATARA FMS',
    'login.subtitle': 'Platform Telemetri & Pengisian Bahan Bakar Industri',
    'login.username': 'Username',
    'login.password': 'Kata Sandi',
    'login.signIn': 'Masuk ke Sistem',
    'login.authenticating': 'Memverifikasi...',
    'login.quickTest': 'Akun Uji Cepat',

    // Common
    'common.liters': 'Liter',
    'common.units': 'Unit',
    'common.hours': 'Jam',
    'common.active': 'Aktif',
    'common.inactive': 'Nonaktif',
    'common.loading': 'Memuat data...',
    'common.save': 'Simpan',
    'common.saving': 'Menyimpan...',
    'common.cancel': 'Batal',
    'common.delete': 'Hapus',
    'common.edit': 'Ubah',
    'common.close': 'Tutup',
    'common.search': 'Cari',
    'common.filter': 'Filter',
    'common.actions': 'Aksi',
    'common.status': 'Status',
    'common.all': 'Semua',
    'common.confirm': 'Konfirmasi',
    'common.noData': 'Tidak ada data',
    'common.success': 'Berhasil',
    'common.error': 'Terjadi kesalahan',
  },
  en: {
    // Nav
    'nav.dashboard': 'Dashboard',
    'nav.dispenser': 'Dispenser Terminal',
    'nav.history': 'Monthly History',
    'nav.backdate': 'Backdate Input',
    'nav.units': 'Fleet Units',
    'nav.tanks': 'Storage Tanks',
    'nav.users': 'User Management',
    'nav.audit': 'Audit Trail',
    'nav.menu': 'Main Menu',
    'nav.networkActive': 'Network Active',

    // Header & Profile
    'header.wita': 'WITA (Site Time)',
    'header.wib': 'WIB',
    'header.shift1': 'Shift 1 (Day)',
    'header.shift2': 'Shift 2 (Night)',
    'header.exportExcel': 'Export Excel',
    'header.sheets': 'Google Sheets',
    'profile.title': 'User Profile',
    'profile.account': 'Account Information',
    'profile.role': 'Role',
    'profile.language': 'Language / Bahasa',
    'profile.languageLabel': 'Language',
    'profile.theme': 'Appearance Theme',
    'profile.themeLabel': 'Theme',
    'profile.darkModeLabel': 'Theme',
    'profile.light': 'Light',
    'profile.dark': 'Dark',
    'profile.signOut': 'Sign Out',
    'profile.logoutLabel': 'Sign Out',

    // Dashboard
    'dash.title': 'Fuel Operations Dashboard',
    'dash.subtitle': 'Solar B35 Inventory, Fleet Dispense Telemetry & Site Sync',
    'dash.liveTelemetry': 'Live Telemetry',
    'dash.siteName': 'PT Batara Perkasa • West Kutai Site',
    'dash.recordDispense': 'Record Dispense (Terminal)',
    'dash.totalDispensedToday': 'Dispensed (Today)',
    'dash.totalDispensedMonth': 'Month-to-Date',
    'dash.totalTransactions': 'Dispense Transactions',
    'dash.inboundRefills': 'Inbound Refill (Supplier)',
    'dash.activeFleet': 'Active Fleet',
    'dash.storageTanksTitle': 'Storage Tank Status',
    'dash.storageTanksSubtitle': 'Solar B35 Industrial Storage Inventory',
    'dash.actualStock': 'Actual Stock',
    'dash.maxCapacity': 'Max Capacity',
    'dash.remainingUllage': 'Remaining Ullage',
    'dash.criticalLimit': 'Critical Low Alert',
    'dash.shiftSummaryTitle': 'Shift & Fleet Telemetry',
    'dash.activeShift': 'Operational Shift',
    'dash.dutyOfficer': 'Duty Officer',
    'dash.recentLogsTitle': 'Recent Refuelling Logs',
    'dash.recentLogsSubtitle': 'Real-time heavy equipment refuelling audit feed',
    'dash.filterPlaceholder': 'Filter unit code (e.g. LV, DT, EX)...',
    'dash.viewFullHistory': 'View Full Monthly History',
    'dash.synced': 'Synced',
    'dash.pending': 'Pending Sync',
    'dash.totalDispensed': 'Fuel Dispensed',
    'dash.totalStock': 'Total Tank Stock',
    'dash.activeUnits': 'Active Fleet Units',
    'dash.openSheets': 'Open Live Google Sheets',
    'dash.downloadExcel': 'Download Monthly Excel Report',
    'dash.noUnit': 'Unit Code',
    'dash.category': 'Category',
    'dash.dateTime': 'Time (WITA)',
    'dash.volume': 'Volume (L)',
    'dash.operator': 'Operator',
    'dash.fuelman': 'Fuelman',
    'dash.viewAll': 'Manage Tanks',
    'dash.fleetDistribution': 'Registered Fleet Distribution',
    'dash.shiftDay': 'Day',
    'dash.shiftNight': 'Night',
    'dash.capacityLabel': 'Capacity',
    'dash.shiftActive': 'Shift 1 & 2 Active',
    'dash.totalRecords': 'Total Site Records',
    'dash.tickets': 'Tickets',
    'dash.filled': 'Filled',
    'dash.loadingTanks': 'Loading storage tank data...',
    'dash.logsCount': 'Displayed',

    // Dispenser Page
    'dispenser.title': 'Fuel Dispensing Terminal',
    'dispenser.subtitle': 'Real-time meter validation, transaction logging, and automated Google Sheets sync',
    'dispenser.fuelDispensed': 'Fuel Dispensed',
    'dispenser.transactions': 'Transactions',
    'dispenser.inboundRefills': 'Inbound Refills',
    'dispenser.dutyOfficer': 'Duty Officer',
    'dispenser.docketTitle': 'Fuel Dispensing Docket',
    'dispenser.docketSubtitle': 'Delta Motor Validation Engine Active',
    'dispenser.keypadOn': 'Keypad On',
    'dispenser.keypadOff': 'Keypad Off',
    'dispenser.selectUnit': 'Select Target Equipment Unit',
    'dispenser.searchUnitPlaceholder': '-- Search or select target fleet unit --',
    'dispenser.odometerKm': 'Current Odometer (KM)',
    'dispenser.prevKm': 'Prev',
    'dispenser.hourMeterHm': 'Current Hour Meter (HM)',
    'dispenser.prevHm': 'Prev',
    'dispenser.dispenseQty': 'Dispense Quantity (QTY OUT - Liters)',
    'dispenser.tapPresets': 'Tap Presets',
    'dispenser.operatorDriver': 'Operator / Driver',
    'dispenser.searchOperatorPlaceholder': 'Search or type operator name...',
    'dispenser.recordAndSync': 'Submit',
    'dispenser.recording': 'Recording Transaction...',
    'dispenser.inspectBaselines': 'Select a Unit to Inspect Baselines',
    'dispenser.inspectDesc': 'Delta calculations compare against last recorded Hour Meter and Odometer in real-time.',
    'dispenser.plateNumber': 'Plate Number',
    'dispenser.status': 'Status',
    'dispenser.lastKm': 'Last KM',
    'dispenser.lastHm': 'Last HM',
    'dispenser.errEnterVolume': 'Please enter dispensed volume in Liters.',
    'dispenser.errEnterOperator': 'Please enter unit driver / machine operator name.',

    // History Page
    'history.title': 'Monthly Historical Records',
    'history.subtitle': 'Browse, backfill, and synchronize historical fuel ledger organized by monthly sheet tabs',
    'history.syncMonth': 'Sync Month',
    'history.syncing': 'Syncing...',
    'history.syncMaster': 'Sync Master Log',
    'history.inputBackdate': 'Input Backdate',
    'history.addEntry': 'Add Entry',
    'history.importExcel': 'Import Excel Data',
    'history.fuelDispensed': 'Fuel Dispensed',
    'history.inboundRefills': 'Inbound Refills',
    'history.restocked': 'Restocked',
    'history.transactions': 'Transactions',
    'history.monthlyRecords': 'Monthly records',
    'history.activeUnits': 'Active Units',
    'history.fuelledFleets': 'Fuelled fleets',
    'history.sheetSync': 'Sheet Tab Sync',
    'history.searchPlaceholder': 'Search unit code, operator, fuelman, or category...',
    'history.shiftFilter': 'Shift',
    'history.allShifts': 'ALL SHIFTS',
    'history.shift1': 'SHIFT 1 (Day)',
    'history.shift2': 'SHIFT 2 (Night)',
    'history.syncFilter': 'Sync',
    'history.allStatus': 'ALL STATUS',
    'history.synced': 'SYNCED',
    'history.pending': 'PENDING',
    'history.failed': 'FAILED',
    'history.colNo': 'NO ID.',
    'history.colUnit': 'UNIT CODE',
    'history.colCategory': 'CATEGORY',
    'history.colMerk': 'MAKE / MODEL',
    'history.colType': 'TYPE',
    'history.colDate': 'DATE',
    'history.colTime': 'TIME',
    'history.colKm': 'KM',
    'history.colHm': 'HM',
    'history.colFuelIn': 'FUEL IN',
    'history.colQtyOut': 'QTY OUT ( L )',
    'history.colOperator': 'OPERATOR',
    'history.colShift': 'SHIFT',
    'history.colFuelman': 'FUELMAN',
    'history.colTank': 'TANK',
    'history.colSync': 'SHEETS SYNC',
    'history.colActions': 'ACTIONS',
    'history.noTransactions': 'No transactions recorded for this period.',
    'history.loadingMonth': 'Loading historical records...',
    'history.dismiss': 'Dismiss',

    // Backdate Page
    'backdate.title': 'Backdate Fuel Input',
    'backdate.subtitle': 'Chronological fuel dispense backfill with strict Hour Meter & Odometer validation.',
    'backdate.preset': 'Preset:',
    'backdate.yesterday': 'Yesterday',
    'backdate.twoDaysAgo': '2 Days Ago',
    'backdate.today': 'Today',
    'backdate.monthlyHistory': 'Monthly History',
    'backdate.close': 'Close',
    'backdate.dateLabel': 'Dispensing Date',
    'backdate.timeLabel': 'Time (WITA)',
    'backdate.shiftLabel': 'Operational Shift',
    'backdate.fuelmanLabel': 'Fuelman on Duty',
    'backdate.selectUnitLabel': 'Select Heavy Equipment Unit',
    'backdate.selectTankLabel': 'Select Storage Tank Source',
    'backdate.operatorLabel': 'Operator / Driver',
    'backdate.qtyLabel': 'Dispensed Volume (QTY OUT - Liters)',
    'backdate.fuelInLabel': 'Inbound Fuel from Supplier (Optional - Liters)',
    'backdate.submit': 'Submit',
    'backdate.saving': 'Saving Backdate Record...',
    'backdate.bypassWarning': 'Validation Bypass Mode Active',
    'backdate.chronologicalSummary': 'Chronological Audit & Meter Bounds',

    // Units Page
    'units.title': 'Master Fleet Equipment',
    'units.subtitle': 'Equipment benchmarks, baseline KM/HM telemetry, and operational status',
    'units.importExcel': 'Import Excel',
    'units.addUnit': 'Register Unit',
    'units.searchPlaceholder': 'Search unit code, plate number, category, or model...',
    'units.colCode': 'UNIT CODE',
    'units.colPlate': 'PLATE NO',
    'units.colCategory': 'CATEGORY',
    'units.colModel': 'MAKE / MODEL',
    'units.colType': 'TYPE',
    'units.colLastKm': 'LAST KM',
    'units.colLastHm': 'LAST HM',
    'units.colStatus': 'STATUS',
    'units.colActions': 'ACTIONS',
    'units.active': 'Active',
    'units.inactive': 'Inactive',
    'units.edit': 'Edit',
    'units.delete': 'Delete',
    'units.modalTitleCreate': 'Register New Equipment Unit',
    'units.modalTitleEdit': 'Edit Equipment Unit',
    'units.unitCodeLabel': 'Unit Code (e.g. DT-01, EX-200)',
    'units.plateLabel': 'License Plate Number',
    'units.categoryLabel': 'Fleet Category',
    'units.typeLabel': 'Vehicle Type',
    'units.modelLabel': 'Make & Model',
    'units.save': 'Save Unit',
    'units.saving': 'Saving...',
    'units.cancel': 'Cancel',
    'units.emptyTitle': 'No equipment units found',

    // Tanks Page
    'tanks.title': 'Solar B35 Storage Tanks',
    'tanks.subtitle': 'Fuel inventory surveillance, safe minimum thresholds, and supplier restock logs',
    'tanks.addTank': 'Register Storage Tank',
    'tanks.recordRefill': 'Record Inbound Refill',
    'tanks.currentStock': 'Current Stock',
    'tanks.capacity': 'Max Capacity',
    'tanks.minAlert': 'Min Alert Level',
    'tanks.availableUllage': 'Available Ullage (Empty Space)',
    'tanks.availableFuel': 'Available Fuel',
    'tanks.full': 'Full',
    'tanks.tankCode': 'Tank Code',
    'tanks.tankName': 'Tank Name',
    'tanks.fuelType': 'Fuel Type / Grade',
    'tanks.capacityL': 'Capacity (L)',
    'tanks.currentStockL': 'Current Stock (L)',
    'tanks.alertLevelL': 'Min Alert Level (L)',
    'tanks.refillModalTitle': 'Record Inbound Fuel Refill',
    'tanks.refillVolume': 'Inbound Volume (Fuel In - Liters)',
    'tanks.refillNotes': 'Delivery / Tanker Notes / DO No.',
    'tanks.saveRefill': 'Save Refill',
    'tanks.saving': 'Saving...',
    'tanks.editTank': 'Edit Tank',
    'tanks.deleteTank': 'Delete Tank',
    'tanks.createModalTitle': 'Register New Storage Tank',
    'tanks.editModalTitle': 'Edit Storage Tank',
    'tanks.deleteConfirm': 'Are you sure you want to permanently delete this storage tank? Tanks with recorded historical fuel logs cannot be deleted.',
    'tanks.confirmDelete': 'Confirm Delete',
    'tanks.confirmInbound': 'Confirm Inbound',
    'tanks.processing': 'Processing...',

    // Users Page
    'users.title': 'User Accounts & Access Control',
    'users.subtitle': 'System access configuration, site personnel onboarding, and security management',
    'users.addUser': 'Add User',
    'users.totalUsers': 'Total Users',
    'users.activeAccounts': 'Active Accounts',
    'users.administrators': 'Administrators',
    'users.fuelmenOfficers': 'Fuelmen / Officers',
    'users.registered': 'registered',
    'users.fieldCrew': 'field crew',
    'users.rootPrivileged': 'root/privileged',
    'users.searchPlaceholder': 'Search by full name, username, or email...',
    'users.roleFilter': 'Role',
    'users.allRoles': 'All Roles',
    'users.admins': 'Admins',
    'users.management': 'Management',
    'users.fuelmen': 'Fuelman',
    'users.statusFilter': 'Account Status',
    'users.allStatus': 'All Status',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.colUser': 'USER / IDENTITY',
    'users.colEmail': 'EMAIL ADDRESS',
    'users.colRole': 'ROLE',
    'users.colStatus': 'STATUS',
    'users.colDispenseLogs': 'DISPENSE LOGS',
    'users.colCreated': 'CREATED',
    'users.colActions': 'ACTIONS',
    'users.loadingUsers': 'Loading user accounts...',
    'users.noUsersFound': 'No users found matching your search criteria.',
    'users.you': 'You',
    'users.clickToDeactivate': 'Click to Deactivate',
    'users.clickToActivate': 'Click to Activate',
    'users.editUser': 'Edit User',
    'users.deleteUser': 'Delete User',
    'users.createModalTitle': 'Create New User Account',
    'users.editModalTitle': 'Edit User',
    'users.username': 'Username',
    'users.systemRole': 'System Role',
    'users.fullName': 'Full Name',
    'users.emailAddress': 'Email Address',
    'users.initialPassword': 'Initial Password',
    'users.resetPassword': 'Reset Password',
    'users.optional': 'optional',
    'users.leaveBlank': 'Leave blank to keep existing password',
    'users.accountStatus': 'Account Status',
    'users.activeDesc': 'Active and allowed to log in',
    'users.inactiveDesc': 'Deactivated account',
    'users.cannotDeactivateSelf': 'You cannot deactivate your own account',
    'users.deleteConfirm': 'Are you sure you want to permanently delete this user? This action is immutable and will be recorded in the audit trail.',
    'users.deleteWarningHasLogs': 'Warning: This user has recorded fuel logs and cannot be hard deleted. You should deactivate them instead.',
    'users.deactivateInstead': 'Deactivate Account Instead',
    'users.confirmDelete': 'Confirm Delete',
    'users.accessRestricted': 'Access Restricted',
    'users.accessRestrictedDesc': 'User Management is privileged and reserved exclusively for authorized system administrators.',
    'users.returnToDispenser': 'Return to Dispenser',

    // Audit Page
    'audit.title': 'System Audit Trail',
    'audit.subtitle': 'Immutable logging of dispensing actions, overrides, and administrative mutations',
    'audit.colTimestamp': 'TIMESTAMP',
    'audit.colAction': 'ACTION',
    'audit.colEntity': 'ENTITY',
    'audit.colUser': 'PERFORMED BY',
    'audit.colIp': 'IP / CLIENT',
    'audit.colDetails': 'MUTATION DIFF / REASON',
    'audit.systemWorker': 'System Worker',

    // Login Page
    'login.title': 'BATARA FMS',
    'login.subtitle': 'Industrial Fuel Telemetry & Dispensing Platform',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.signIn': 'Sign In',
    'login.authenticating': 'Authenticating...',
    'login.quickTest': 'Quick Test Credentials',

    // Common
    'common.liters': 'Liters',
    'common.units': 'Units',
    'common.hours': 'Hours',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.loading': 'Loading data...',
    'common.save': 'Save',
    'common.saving': 'Saving...',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.all': 'All',
    'common.confirm': 'Confirm',
    'common.noData': 'No data available',
    'common.success': 'Success',
    'common.error': 'Error occurred',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'id',
  setLang: () => {},
  t: (key: string, fallback?: string) => fallback || key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>('id');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const saved = localStorage.getItem('fms_lang') as Language;
    if (saved === 'id' || saved === 'en') {
      setLangState(saved);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('fms_lang', newLang);
  };

  const t = (key: string, fallback?: string): string => {
    return translations[lang]?.[key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
